assets:
  settings.xml: "davherrmann/rultor-config#assets/settings.xml"
  pubring.gpg: "davherrmann/rultor-config#assets/pubring.gpg"
  secring.gpg: "davherrmann/rultor-config#assets/secring.gpg"
docker:
  image: davherrmann/java8maven
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Prelease --settings /home/r/settings.xml
