language: java

jdk:
  - oraclejdk8

dist: trusty
addons:
  apt:
    packages:
      oracle-java8-installer

after_success:
  # run jacoco, send report to coveralls.io
  - mvn clean test jacoco:report coveralls:report
  
  # install and run codacy-coverage-reporter
  - curl http://www.jpm4j.org/install/script | sudo sh
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
  - codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml
  
  # deploy snapshot to sonatype
  - echo "<settings><servers><server><id>oss.sonatype.org</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy -DskipTests --settings ~/settings.xml
